/*** Names for effects ***/
export const COMPRESSOR = 'COMPRESSOR';
export const DELAY = 'DELAY';
export const DISTORTION = 'DISTORTION';
export const DUB = 'DUB';
export const FLANGER = 'FLANGER';
export const PING_PONG = 'PING_PONG';
export const QUADRAFUZZ = 'QUADRAFUZZ';
export const REVERB = 'REVERB';
export const RING_MOD = 'RING_MOD';
export const STEREO_PANNER = 'STEREO_PANNER';
export const TREMOLO = 'TREMOLO';
